[workspace]

members = [
  "nucliadb_std",
  "nucliadb_relations",
  "nucliadb_telemetry",
  "nucliadb_protos/rust",
  "nucliadb_cluster",
  "nucliadb_node",
  "nucliadb_node/binding",
  "nucliadb_services",
  "nucliadb_ftp",
  "vectors_benchmark"
]
