{{ $count := .Values.replicaCount | int }}
{{ $release := .Release }}
{{ $chart := .Chart }}
{{- range $index, $ := until $count }}
kind: Service
apiVersion: v1
metadata:
  name: node-reader-{{ $index }}
  labels:
    app: node-reader-{{ $index }}
    version: "{{ $chart.Version | replace "+" "_" }}"
    chart: "{{ $chart.Name }}"
    release: "{{ $release.Name }}"
    heritage: "{{ $release.Service }}"
spec:
  type: ClusterIP
  selector:
    app: node-reader-{{ $index }}
  ports:
    - name: node-reader
      port: 10001
      protocol: TCP
      appProtocol: grpc
{{- end }}