{{- range $index, $ := until .Values.replicaCount }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-reader-{{ $index }}
    app.kubernetes.io/name: node-reader
    app.kubernetes.io/instance: {{ .Release.Name }}-{{ $index }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    version: "{{ .Chart.Version | replace "+" "_" }}"
    chart: "{{ .Chart.Name }}"
  name: node-reader-{{ $index }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-reader-{{ $index }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "{{.Values.nats.port }}"
        traffic.sidecar.istio.io/excludeInboundPorts: "{{.Values.serving.metricsPort }}"
        # do not have access to dependency chart cm this component references
        checksum/cm: {{ include (print $.Template.BasePath "/node.cm.yaml") . | sha256sum }}
      labels:
        app: node-reader-{{ $index }}
        app.kubernetes.io/instance: node-reader-{{ $index }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        version: "{{ .Chart.Version | replace "+" "_" }}"
        chart: "{{ .Chart.Name }}"
      name: node-reader-{{ $index }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nuclia.cloud/nodepool
                    operator: In
                    values:
                      - nucliadb-node
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: statefulset.kubernetes.io/pod-name
                    operator: In
                    values:
                      - node-{{ $index }}
              topologyKey: kubernetes.io/hostname
      tolerations:
        - effect: NoSchedule
          key: nucliadb/node
          operator: Equal
          value: present
      containers:
        - command:
            - node_reader
          env:
            - name: METRICS_HTTP_PORT
              value: "3031"
            - name: EXAMPLE
              value: VALUE
          envFrom:
            - configMapRef:
                name: node-config
          image: eu.gcr.io/stashify-218417/node:b7e3f15
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:10001
                - -service=nodereader.NodeReader
            failureThreshold: 3
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: node-reader
          ports:
            - containerPort: 10001
              name: grpc-reader
              protocol: TCP
            - containerPort: 3031
              name: metrics
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:10001
                - -service=nodereader.NodeReader
            failureThreshold: 10
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: node-pv
{{- if .Values.tracing.enabled }}
        - name: jaeger-agent
          image: "jaegertracing/jaeger-agent:{{ .Values.tracing.jaegerAgentTag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
              name: zk-compact-trft
              protocol: UDP
            - containerPort: 5778
              name: config-rest
              protocol: TCP
            - containerPort: 6831
              name: jg-compact-trft
              protocol: UDP
            - containerPort: 6832
              name: jg-binary-trft
              protocol: UDP
            - containerPort: 14271
              name: admin-http
              protocol: TCP
          args:
            - --reporter.grpc.host-port=dns:///{{ .Values.tracing.jaegerCollectorHost }}:{{ .Values.tracing.jaegerCollectorGrpcPort }}
            - --reporter.type=grpc
{{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      volumes:
        - name: nats-creds
          secret:
            defaultMode: 420
            secretName: nats-nucliadb-creds
        - name: regional-nats-creds
          secret:
            defaultMode: 420
            secretName: nats-regional-creds
        - name: node-pv
          persistentVolumeClaim:
            claimName: node-pv-node-{{ $index }}
{{- end }}