name: NucliaDB SDK (py)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # Job to run pre-checks
  pre-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install package
        run: make -C nucliadb_sdk/ install-dev

      - name: Run pre-checks
        run: make -C nucliadb_sdk/ lint

  # Job to run tests
  tests:
    name: NucliaDBSDKTests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install the package
        run: make -C nucliadb_sdk/ install-dev

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            nucliadb_modified:
              - 'nucliadb/**'
            nucliadb_node_modified:
              - 'nucliadb_node/**'
              - 'nucliadb_core/**'
              - 'nucliadb_paragraphs/**'
              - 'nucliadb_texts/**'
              - 'nucliadb_vectors/**'
              - 'nucliadb_relations/**'

      - name: Get safe branch name
        id: branch_name
        run: |-
          BRANCH_NAME=`echo $GITHUB_HEAD_REF | sed 's$/$-$g'`
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Wait for nucliadb image
        if: ${{ steps.filter.outputs.nucliadb_node_modified == 'true' || steps.filter.outputs.nucliadb_modified == 'true' }}
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ steps.branch_name.outputs.branch_name }}
          check-name: DevNucliaImage
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      
      - name: Set node image tag
        if: ${{ steps.filter.outputs.nucliadb_node_modified == 'true' || steps.filter.outputs.nucliadb_modified == 'true' }}
        run: |
          echo "NUCLIADB_IMAGE_VERSION=dev-${{ steps.branch_name.outputs.branch_name }}" >> $GITHUB_ENV
      
      - name: Set node image tag
        if: ${{ steps.filter.outputs.nucliadb_node_modified == 'true' || steps.filter.outputs.nucliadb_modified == 'true' }}
        run: |
          echo "NUCLIADB_IMAGE_NAME=eu.gcr.io/stashify-218417/nucliadb" >> $GITHUB_ENV"

      - name: Run tests
        run: |
          pytest -rfE --cov=nucliadb_sdk -s --tb=native -v --cov-report xml --cov-append nucliadb_sdk/nucliadb_sdk

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: sdk
